# 2019136011 권성민 

## a_tensor_initialization.py

In [1]:
import torch

torch package를 현재 prompt에 include한다.

In [2]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


python의 [1,2,3] 리스트를 torch의 Tensor 객체로 CPU에서 사용한다.
torch의 Tensor 객체는 기본 값 데이터 자료형으로 torch.float32을 사용한다.
device는 cpu 혹은 gpu에서 작동을 하는데 cpu에서 작동한다는 것을 나타낸다.
requires_grad는 pyTorch의 자동 미분 엔진을 사용하는지 여부를 나타낸다. 현재는 기본 값인 False로 사용하지 않는다.
size()로는 [3]으로 생성자의 인자가 [1,2,3]이므로 1차원 tensor에 요소로 3개가 있다는 뜻이다.
shape는 size()와 동일한 값으로, 멤버 변수로 불러올 수도 있다.

In [19]:
#if you have gpu device
t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

t1.to(torch.device('cuda')) 와 t1.cuda()의 방법으로 RAM 메모리에 있는 값을 GPU의 메모리로 옮긴다.
반대로 t1.cpu()와 같이 멤버 함수로 GPU에서 RAM으로 옮길 수도 있다.

In [20]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4


a1과 a2를 비교해보면 a1은 값 자체를 넘겨주고, a2는 리스트 형태로 넘겨준다.
따라서 a1의 차원은 0차원으로 점의 형태이고, a2의 경우 1차원 tensor이며 element는 1개가 있다.. 
a3의 경우 1차원 tensor로 elements가 5개이다.
a4의 경우 2차원 tensor로, 1차원 tensor의 집합을 tensor로 갖으므로 2차원 tensor이다.
a5의 겨웅 마찬가지로 2차원 tensor로 elements가 2개인 1차원 tensor 3개를 array로 갖는 2차원 tensor이다.
a6의 경우 3차원 tensor이다. 1개의 element를 요소로 갖는 1차원 tensors가 있고 이러한 1차원 tensors를 2개씩 element로 갖는 2차원 tensors와, 2차원 tensors를 3개를 element로 갖는 3차원 tensor가 바로 a6이다.
a7의 경우 4차원 tensor로 a6와 유사한 방식으로 볼 수 있다.

In [21]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a11.shape, a11.ndim)

a12 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

a8은 4차원 tensor로 위 주석에서 설명한 것과 유사하게 확인할 수 있다. 이러한 복잡한 tensor의 경우 ']'가 나오기 이전까지의 '['의 갯수를 세어서 차원을 추측할 수 있다. 
a9도 위에서 설명한 방법을 기반으로 ']'가 나오기 이전에 '['가 [[[[[으로 5개이므로 5차원 tensor이다.
a10은 2차원 tensor로 5개의 elements를 갖는 1차원 tensor가 4개로, [4,5] shape의 2차원 tensor이다.
a11은 3차원 tensor로 [의 수를 통해 확인할 수 있다. 5개의 elements를 갖느 1차원 tensor를 element로 1개씩 있는 2차원 tensor와, 이러한 tensor를 4개로 갖는 3차원 tensor가 a11이다. 따라서 shape는 [4,1,5]이다.
a12는 오류가 발생하는 경우로 왜냐하면 tensor는 array이기 때문이다. array라 함은 각 차원에서 요소가 동일해야 한다. 따라서 [1,2,3]을 [1,2]로 바꾸던가 [4,5]를 [4,5,6]으로 변경해야 한다.

## b_tensor_initialization.py

In [22]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


해당 prompt에서는 torch와 numpy를 사용하며 numpy와 python list를 tensor로 변경하는 예제이다.
l1, l2, l3은 python의 list를 tensor로 변경하는 방법을 예제로 보여준다.
결과를 보면 torch.Tensor로 생성하는 경우 생성자를 통해 생성하므로 Tensor의 기본 자료형인 torch.FloatTensor로 생성되는 것을 볼 수 있다.
이에 반해서 tensor와 as_tensor 멤버 함수의 경우 입력된 값의 데이터 자료형을 받아서 생성하므로 torch.IntTensor로 생성되는 것을 볼 수 있다.
또한 원래 자료형의 값을 변경했음에도 tensor의 값은 변경되지 않는다. 이는 모두 deep copy를 사용한다는 것을 볼 수 있다.

l4,l5,l6은 numpy의 array를 tensor로 만드는 과정이다.
마찬가지로 torch.Tensor는 생성자이므로, 데이터 자료형을 Float로 만드는 반면에 tensor와 a_tensor는 Int 자료형으로 만들어지는 것을 볼 수 있다.
이때 주의 해야 할 점으로 numpy array를 as_tensor로 만드는 경우 shallow copy가 발생한다는 점을 볼 수 있다.

## c_tensor_initialization_constant_values.py

In [23]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1.4013e-45, 0.0000e+00, 4.0627e-12, 8.1836e-43])
tensor([1.4013e-45, 0.0000e+00, 4.0613e-12, 8.1836e-43])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


torch.ones는 주어진 size에 맞춰서 array를 만든다. 이때 1로 초기화하는 것을 의미한다. 따라서 [5,]의 size로 들어왔기 때문에 [1,1,1,1,1]로 1차원 tensor를 만든다. ones_like는 입력된 tensor와 동일한 size의 tensor를 1로 초기화하여 반환한다.

zeros와 zeros_like는 ones와 다르게 0으로 초기화하여 반환한다.

empty 또한 ones와 동일하지만, 쓰레기 값이 들어간다.

eye의 경우 n x n 크기의 Identity Matrix를 만들어 반환한다.

## d_tensor_initialization_random_values.py

In [11]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[16, 17]])
tensor([[0.8083, 0.4360, 0.1718]])
tensor([[-0.1120,  0.1259,  0.2672]])
tensor([[11.1580, 10.5840],
        [10.0479,  8.5969],
        [ 9.3034, 10.5792]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


torch.randint는 [10,20)의 랜덤 값을 갖으며, tensor의 shape는 size로 들어온 [1,2]의 2차원 tensor를 만든다.
이에 반해 torch.rand는 [0,1] 사이의 실수를 size 인자로 들어온 [1,3]의 2차원 tensor를 만든다.
torch.randn은 표준 정규 분포에서 sampling한 값을 꺼내며, 평균은 0, 분산은 1인 [0,1] 범위에서 들어온 size 인자에 맞춰서 tensor를 반환한다.
torch.normal은 정규 분포에서 sampling한 값을 꺼내며 평균과 분산은 인자로 들어온 값에 따라 달라진다.
torch.linspace는 1차원 tensor를 반환한다. 이때 인자로 범위가 주어지며, 인자인 steps에 따라서 해당 범위를 steps만큼의 n등분하여 각 값을 반환한다.
torch.arrange는 1차원 tensor를 반환하며, 인자로 들어온 값으로 [0, argument)까지 반환한다.

torch.manual_seed는 random을 위한 seed로 랜덤은 seed에서 복잡한 연산을 통해 중복되지 않는 값을 random으로 뽑는게 원리이므로, seed를 고정하여 같은 순서의 랜덤 값으로 나오게 한다.
torch.rand를 통해 seed를 동일하게 설정 시 같은 값이 나오는 것을 볼 수 있다.

## e_tensor_type_conversion.py

In [12]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


dtype 인자를 사용하여서 원하는 a, b 변수를 통해 볼 수 있다. Tensor가 기본적으로 torch.float32이지만, int16으로 dtype 인자를 주어 2바이트 int형으로 만든다.
c는 rand로 float64 데이터 자료형으로 [0,1] 범위의 반환을 한다. 이때 20을 곱하는데 broadcast로 [0,20]의 범위의 rand으로 반환한다.
d는 2바이트 int형을 4바이트 int형으로 변경하여 반환하는 것을 볼 수 있다.

print(short_e.dtype) 까지의 코드는 인자로 주는 방법 외에도 멤버 함수를 통해서 다른 타입으로 변경하는 것을 보여준다. ( .데이터자료형 , .to(데이터자료형) )
그 다음 예제는 다른 데이터 자료형끼리의 연산으로 일반적으로 다른 언어에서와 마찬가지로 더 큰 자료형의 데이터 타입으로 변경해서 연산하는 것을 볼 수 있다.

## f_tensor_operations.py

In [13]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


첫 번째 예제는 명시적으로 torch의 멤버 함수를 통해 더하는 방법과, operation override된 operator를 사용하여 연산하는 것을 보여준다. 각 값은 같은 것을 볼 수 있다.

2번째 예제는 add가 아닌 substract에 대한 예제로 add와 동일한 설명이다.
3번째 예제는 multiply로 곱 연산에 대한 예제로 add와 동일한 설명이다.
4번째 예제는 division에 대한 예제로 add와 동일한 설명이다.

여기서의 연산은 같은 위치의 elements 사이의 연산을 의미한다.
또한 broadcasting 연산이 없다.

## g_tensor_operations.mm.py

In [14]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


각 예제는 선형대수에 대한 예제이다.
첫 번째 dot product 연산은 보면 shape가 다른 tensor끼리의 dot product를 보여준다. 이때 작은 차원의 tensor가 더 큰 차원의 tensor의 차원(+ element count)에 맞춰서 더 작은 차원의 값을 복사해서 같은 shape로 맞춘 후 dot product 연산을 진행한다. dot product의 연산 결과는 Scalar 값이므로 0차원 tensor가 나온다.

2번째 예제는 matrix multiply의 연산으로 행렬연산을 진행한다. 2 x 3 행렬과 3 x 2 행렬의 연산으로 2 x 2 행렬 연산 결과가 나오는 것을 볼 수 있다.
여기서 mm은 broadcasting 연산이 없다.

3번쨰 예제는 batch matrix multiply의 연산으로 3x4 Matrix와 4 x 5 Matrix를 batch 단위로(10) 연산하여 [10,3,5]의 shape tensor가 나오는 것을 볼 수 있다.
여기서 bmm은 broadcastring 연산이 없다.

## h_tensor_operations_matmul.py

In [15]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


첫 번째 예제는 0차원 tensor에 대해서 multiple matrix multiply에 대해 한다. 따라서 0차원 tensor가 결과로 나온다. (dot product)
mm과의 차이점으로 braodcasting 연산이 지원된다.

두 번째 예제는 3개를 batch로 삼는 t3 tensor(4 elements vector)와 4 elements vector간의 matrix multiply(dot product)를 진행한다.
shape가 맞지 않기 때문에 broadcasting이 되어서 t4가 3개의 batch로 broadcasting이 된다. 이때 dot product의 연산으로 Scalar 값이 나오므로 1차원 tensor가 반환된다.

세 번째 예제 또한 broadcasting에 대한 결과로 t6이 [10,3,4]로 broadcasting이 되어 [10,3]의 batch를 갖고 dot product 연산이 지원된다.

네 번째 예제는 10을 batch로 갖고 3x4 matrix와 4x5 matrix 사이의 연산이 되어 [10,3,5]의 결과가 나온다.

다섯 번째 예제는 t10이 broadcasting이 되어 10을 batch로 갖고, 3x4 matrix와 4x5 matrix의 곱으로 [10,3,5]의 shape의 tensor를 반환한다.

## i_tensor_broadcasting.py

In [26]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)




tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


첫 예제는 elements broadcasting에 대한 것으로 각 요소에 2씩 곱하여 결과가 나온다.
두 번째 예제, t3은 [3,2] shape tensor와 [2] shape에 대한 tensor의 subtract에 대한 연산으로 broadcasting되어 [[0-4,1-5],[2-4,4-5],[10-4,10-5]]이 결과로 나온다.
세 번째 예제는 값에 .을 붙여 torch.float32으로 입력된 값이다.
그리고 각 연산에 대해서 elements 사이에 broadcasting되어 결과를 나타낸다. 

In [30]:

def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


normalize 함수를 선언한다 후에 image에 대한 normalize를 하기 위한 것으로 추측된다.
shape[3,28,28]의 tensor로 normalize에 대한 결과도 element 연산이기 때문에 사이즈가 유지되는 것을 볼 수 있다.

그 다음 예제는 element operation에 대해서 broadcasting 연산되어 큰 차원으로 변경 되어서 연산 결과가 나오는 것을 볼 수 있다.

마지막 예제 또한 broadcasting 연산 후 elements에 대한 operation 연산 결과 더 큰 차원으로 유지되는 것을 볼 수 있다.

In [37]:
print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


마찬가지로 더 큰 차원으로 변환되는 것을 볼 수 있다. 보면 차원이 잘 맞지 않는 것이 보인다. broadcasting은 last to first이기 때문에 t19의 [,,4,1]이 t20의 [,1,1]이 broadcasting되어 [,,4,1]이 되고 [5,1,,]과 [,3,,] 사이에 broadcasting되어 [5,3,4,1]이 된다. 나머지 또한 큰 차원에 대해서 broadcasting 된다.

pow 연산 또한 element에 대한 연산임을 볼 수 있다.

## j_tensor_indexing_slicing.py

In [39]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2


slicing은 [ , ) 집합으로 마지막 값은 exclusive된다. ':'만 있는 경우 모든 값을 얘기한다.
따라서 각 차원에 대해서 값을 뽑는데 사용된다. -1의 경우는 마지막 index를 얘기한다.

In [41]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


1:4는 [1,4)로 1~3번째 index까지 뽑는다.
이러한 index slicing을 통해서 특정 값을 얻어오거나 변경할 수도 있다.

## k_tensor_reshaping.py

In [43]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2


첫 번째 예제로는 tensor를 같은 값으로 shape 형태를 변경하는 것이다.
view와 reshape는 shallow copy로 값이 공유된다.
다만 차이점으로는 view의 경우 데이터가 연속적으로 되지 않을 경우 오류가 발생한다. 

In [55]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


unsqueeze는 해당 인자의 n+1 번째 위치에 dimension을 추가한다.
따라서 첫 번째 print를 보면 (3,)의 1차원 tensor에서 1을 인자로 줄 경우 (3,1)로 2차원 tensor가 된다.
flatten의 경우 여러 차원으로 되어있는 tensor를 1차원 tensor로 펼친다.
하지만 start_dim으로 1일 시 1차원부터 나머지 end_dim까지의 flatten한다. (즉, start_dim부터 flatten한다.)

In [47]:

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


permute 함수의 경우 차원의 순서를 변경한다.
(2,0,1) 일 경우에 (0,1,2)의 순서에서 변경하는 것이다.
shape(2,3)에서 permute(1,0) 시 [[1,2,3],[4,5,6]]에서 [[1,4],[2,5],[3,6]]으로 shape(3,2)로 된다.
transpose는 선형대수학의 transpose와 같다. 

## I_tensor_concat.py

In [53]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)


t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

concat과 cat은 같은 함수이다.
해당 함수는 인자로 들어온 dim에서 연결을 하여 하나의 tensor로 만든다.
2번째 예제에서 보듯이 dim에 있는 차원이 아닌 곳의 차원은 유지가 된다.


## m_tensor_stacking.py

In [54]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


stack 함수의 경우 unsqueeze + concat이 합쳐진 것이다.
따라서 stack 으로 만든 tensor와 unsqueeze + concat한 것으로 같은 값이 나오는 것이 보인다.

## n_tensor_vstack_hstack.py

In [58]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


vstack은 row-wise(vertically)로 stack을 실행하는 것이고, hstack은 col-wise(horizontally)로 stack을 실행하는 것이다.
기본적으로 torch는 (row, col)으로 볼 수 있다. 
따라서 vstack으로 하면 row에서 합쳐지고, hstack을 할 경우 col에서 합쳐진다.